### ISSUE TITLE
how to manage URI path filtering ?

### ISSUE THREAD

**Issue by agaldemas** [factorial-io/haproxy-config#3]
First congratulations !
KISS but S for Smart, and a good idea of simple HMI (Human Machine Intelligence ;O)
I'm a newbie in haproxy, so that your smart haproxy autoconfigure container is very helpful.

Nevertheless I have a question how is it possible to manage URI path filtering ?
like taking `VHOST=<host>:<port>/<path>` to redirect to a backend container `@ VPORT=<xxxxx>`
I tested, it's not possible through REDIRECT_FROM (because no URI path extraction) 
 Should it be possible with VHOST_REGEX ?, I don't think so, some modifications are necessary 

May be it it's not a really pertinent feature, but it could be possible to add a new env variable VPATH, from which a "path_beg" acl rule should be added in the configuration file to achieve path filtering ?

**Comment by stmh** [comment]
thanks for looking into this project. Adding VPATH might be a useful feature, but I am currently busy with other stuff and it might take some time before I can implement this. 

Feel free to fork the repo, implement the feature and create a Pull Request. I am more than happy to review it.

**Comment by agaldemas** [comment]
Thanks for your feedback, I understand, I'm also busy for the moment.

**Comment by stmh** [comment]
Just a quick update. there is now preliminary support for VPATH in the develop branch
